# Environment
domain: ALE # MuJoCo
env: Pong-v5 # InvertedPendulum-v5
render_mode: rgb_array
#max_episode_steps: 100

action_type: Null
state_type: Null
architecture: MLP
mode: 0
action_space: Null
obs_space: Null
action_dim: Null

#Atari Settings (some for Box2D CarRacing)
obs_type: rgb # [rgb, ram, greyscale]
frame_stack: 4 # only works if obs_type=pixels
frameskip: 4
max_episode_steps: False
action_repeat: 1 # set to 2 for pixels
noop_max: 30
grayscale_obs: True
scale_obs: False