defaults:
    - _self_
    - environment
    - sac
    
# Experiment level parameters
experiment_type: State-Vis-Pretraining
test: PEBBLE
device: cpu
num_seed_steps: 5e2 # Steps that the agent does random actions to fill the buffers 5e3 for continuous
num_unsup_steps: 100 #5000
num_train_steps: 5e6 #1e6 for continuous
episodes_to_gen: 10
deploy_mode: True

# logger
log_frequency: 1
log_save_tb: False

# video recorder (Use only in evaluation)
save_video: false
video_location: ${models_dir}/env_traj_gen_clips/
record_frequency: 1

# setups
seed: 1
debug: False
log_success: True

models_dir: ${output_dir}/${algorithm.name}_${test}/seed-${seed}

# All output from experiments
output_dir: results/${experiment_type}/${domain}/${env}
