defaults:
    - _self_
    - environment

algorithm:
    name: SAC

condition: ${algorithm.name} == 'SAC'
optional: sac
    
# Experiment level parameters
experiment_type: State-Vis-Pretraining
device: cpu
cpu_id: 0
deploy_mode: True
overwrite_trajectories: False
sample_size: 30
sampling_rate: 1
fps: 30
# overwrite_videos: True
vis_dir_name: Trajectory_visualisations
label: Null
export_clips: False

# setups
seed: 1
debug: False

# models_dir: ${output_dir}/${algorithm.name}_${test}/seed-${seed}

# All output from experiments
output_dir: results/${experiment_type}/${domain}/${env}
